/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//josh was here 0
package ui;

import db.DBManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kuhail
 */
public class AccountsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountsFrame
     */
    DBManager DB;
    String employee_id;
    String[] columns=new String [] {
                "Account ID", "Customer ID", "Customer Name", "Open Date", "Status", "Type"
            };
    public AccountsFrame(DBManager DB, String employee_id) {
        this.setTitle("Accounts Overview");
        this.DB=DB;
        this.employee_id=employee_id;
        initComponents();
        this.populate_accounts_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        accounts_table = new javax.swing.JTable();
        edit_button = new javax.swing.JButton();
        refresh_button = new javax.swing.JButton();
        search_box = new javax.swing.JTextField();
        delete_button = new javax.swing.JButton();
        add_account_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accounts_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "Customer ID", "Customer Name", "Open Date", "Status", "Type"
            }
        ));
        jScrollPane1.setViewportView(accounts_table);

        edit_button.setText("Edit");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        refresh_button.setText("Refresh");
        refresh_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_buttonActionPerformed(evt);
            }
        });

        search_box.setToolTipText("write customer's names to find accounts");
        search_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_boxKeyReleased(evt);
            }
        });

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        add_account_button.setText("New Account");
        add_account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_account_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add_account_button)
                        .addGap(18, 18, 18)
                        .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(refresh_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_button)
                    .addComponent(refresh_button)
                    .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button)
                    .addComponent(add_account_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_buttonActionPerformed
        // TODO add your handling code here:
        populate_accounts_table();
    }//GEN-LAST:event_refresh_buttonActionPerformed

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        // TODO add your handling code here:
        int row = this.accounts_table.getSelectedRow();
        if(row>=0){
            String account_id=(String)accounts_table.getValueAt(row, 0);
            String status=(String)accounts_table.getValueAt(row, 4);
            DB.changeAccountStatus(account_id, employee_id, status);
        }
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void search_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyReleased
        // TODO add your handling code here:
        Object[][] accounts_data=DB.getAccounts(employee_id,this.search_box.getText());
        this.accounts_table.setModel(new DefaultTableModel(accounts_data,columns));

    }//GEN-LAST:event_search_boxKeyReleased

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        int row = this.accounts_table.getSelectedRow();
        boolean result=false;
        if(row>=0){
            String account_id=(String)accounts_table.getValueAt(row, 0);
            result=DB.deleteAccount(account_id, employee_id);
        }
        
        if(result){
             JOptionPane.showMessageDialog(this,
    "Account was deleted correctly",
    "Confirmation",
    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void add_account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_account_buttonActionPerformed
        // TODO add your handling code here:
        AddAccountFrame addFrame=new AddAccountFrame(this,DB,employee_id);
        addFrame.setVisible(true);
    }//GEN-LAST:event_add_account_buttonActionPerformed

public void populate_accounts_table(){
    Object[][] accounts_data=DB.getAccounts(employee_id);
    this.accounts_table.setModel(new DefaultTableModel(accounts_data,columns));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accounts_table;
    private javax.swing.JButton add_account_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh_button;
    private javax.swing.JTextField search_box;
    // End of variables declaration//GEN-END:variables
}
