/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Controller;
import static java.lang.Float.parseFloat;

/**
 * @author christopheraramswayne
 * @author xjosh
 */
public class EditView extends javax.swing.JFrame {

    
    private int userID;
    private Controller master;
    private String newTitle;
    private String newDescription;
    private float newPrice;
    private int advID;
    /**
     * Creates new form EditView
     */
    public EditView(Controller c, int advID, int usrID) {
        initComponents();
        
        master = c;
        
        this.advID = advID;
        this.userID = usrID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitEdit_Button = new javax.swing.JButton();
        newTitle_Label = new javax.swing.JLabel();
        newDescription_Label = new javax.swing.JLabel();
        newPrice_Label = new javax.swing.JLabel();
        newTitle_Field = new javax.swing.JTextField();
        newDescription_Field = new javax.swing.JTextField();
        newPrice_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submitEdit_Button.setText("Submit Edit");
        submitEdit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEdit_ButtonActionPerformed(evt);
            }
        });

        newTitle_Label.setText("New Title:");

        newDescription_Label.setText("New Description:");

        newPrice_Label.setText("New Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newDescription_Label)
                    .addComponent(newPrice_Label)
                    .addComponent(newTitle_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitEdit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newDescription_Field)
                        .addComponent(newTitle_Field)
                        .addComponent(newPrice_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTitle_Label)
                    .addComponent(newTitle_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDescription_Label)
                    .addComponent(newDescription_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPrice_Label)
                    .addComponent(newPrice_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitEdit_Button)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitEdit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEdit_ButtonActionPerformed
        // TODO add your handling code here:
        
       
       //if field is blank do not update that field
       this.newTitle = newTitle_Field.getText();
       this.newDescription = newDescription_Field.getText();
       this.newPrice = parseFloat(newPrice_Field.getText());
       master.handleEditRequest(newTitle, newDescription, newPrice, userID);
    }//GEN-LAST:event_submitEdit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField newDescription_Field;
    private javax.swing.JLabel newDescription_Label;
    private javax.swing.JTextField newPrice_Field;
    private javax.swing.JLabel newPrice_Label;
    private javax.swing.JTextField newTitle_Field;
    private javax.swing.JLabel newTitle_Label;
    private javax.swing.JButton submitEdit_Button;
    // End of variables declaration//GEN-END:variables
}
