package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Controller.Controller;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author christopheraramswayne
 */
public class ModView extends javax.swing.JFrame {

    private Controller master;
    private String category;
    private String keyword;
    private String months_ago;
    private String advID;
    private String userID;
    private String username;
    private boolean approval;
    
    private Object[] unclaimedAdvertisementsTableColumns = { "ID", "Title", "Description", "Price" , "Date", "Username" };
    private Object[] myAdvertisementsTableColumns = { "ID" , "Title", "Description", "Price", "Status", "Date", "Username" };
    
    
    /**
     * Creates new form UserView
     */
    public ModView(Controller c, String userID, String username) {
        initComponents();
        noSTDresultsLabel.setVisible(false);
        noMyResultsLabel.setVisible(false);
        master = c;
        this.userID = userID;
        this.username = username;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myAdvertisementsTabPane = new javax.swing.JTabbedPane();
        advertisementsPanel = new javax.swing.JPanel();
        categoryLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        periodComboBox = new javax.swing.JComboBox<>();
        periodLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        unclaimedAdvertisementsTable = new javax.swing.JTable();
        claimAdButton = new javax.swing.JButton();
        noSTDresultsLabel = new javax.swing.JLabel();
        myAdvertisementsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myAdvertisementsTable = new javax.swing.JTable();
        approveButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        noMyResultsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoryLabel.setText("Category:");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Electronics", "Cars and Trucks", "Housing", "Child Care" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        periodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last 3 Months", "Last 6 Months", "Last 12 Months", "Life" }));
        periodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodComboBoxActionPerformed(evt);
            }
        });

        periodLabel.setText("Period:");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        descriptionLabel.setText("Title, Description:");

        unclaimedAdvertisementsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Date", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        unclaimedAdvertisementsTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(unclaimedAdvertisementsTable);

        claimAdButton.setText("Claim Ad");
        claimAdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimAdButtonActionPerformed(evt);
            }
        });

        noSTDresultsLabel.setText("No results found.");

        javax.swing.GroupLayout advertisementsPanelLayout = new javax.swing.GroupLayout(advertisementsPanel);
        advertisementsPanel.setLayout(advertisementsPanelLayout);
        advertisementsPanelLayout.setHorizontalGroup(
            advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(advertisementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryLabel)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advertisementsPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(periodLabel))
                    .addGroup(advertisementsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(periodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advertisementsPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(443, 443, 443))
                    .addGroup(advertisementsPanelLayout.createSequentialGroup()
                        .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goButton)
                        .addGap(18, 18, 18)
                        .addComponent(noSTDresultsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(claimAdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        advertisementsPanelLayout.setVerticalGroup(
            advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertisementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(periodLabel)
                    .addComponent(descriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claimAdButton)
                    .addComponent(goButton)
                    .addComponent(noSTDresultsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        myAdvertisementsTabPane.addTab("Unclaimed Advertisements", advertisementsPanel);

        myAdvertisementsPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                myAdvertisementsPanelComponentShown(evt);
            }
        });

        myAdvertisementsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Status", "Date", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myAdvertisementsTable.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(myAdvertisementsTable);

        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Disapprove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disapproveButtonActionPerformed(evt);
            }
        });

        noMyResultsLabel.setText("No results found.");

        javax.swing.GroupLayout myAdvertisementsPanelLayout = new javax.swing.GroupLayout(myAdvertisementsPanel);
        myAdvertisementsPanel.setLayout(myAdvertisementsPanelLayout);
        myAdvertisementsPanelLayout.setHorizontalGroup(
            myAdvertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAdvertisementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noMyResultsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        myAdvertisementsPanelLayout.setVerticalGroup(
            myAdvertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myAdvertisementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myAdvertisementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveButton)
                    .addComponent(jButton1)
                    .addComponent(noMyResultsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        myAdvertisementsTabPane.addTab("Claimed Advertisements", myAdvertisementsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myAdvertisementsTabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(myAdvertisementsTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //When the "Go" button is pressed, the view will tell the controller that the
    //button was pushed. The controller will be given the query terms to handle
    //a request to fill the table
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        category=categoryComboBox.getSelectedItem().toString();
        months_ago = periodComboBox.getSelectedItem().toString();
        keyword = descriptionTextField.getText();
        master.handleModSTDTableRequest(userID, category, months_ago, keyword);

        // TODO add your handling code here
    }//GEN-LAST:event_goButtonActionPerformed

    //Combobox should change the String "Category" to whatever is currently selected
    //in the ComboBox
    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    //Approve button retrieves the selected row, and passes the selected Advertisement's 
    //ID to to the Controller to have the approval status changed.
    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        int row = this.myAdvertisementsTable.getSelectedRow();
        approval = true;  ////true means approved
                
        if(row>=0){
            advID=(String)myAdvertisementsTable.getValueAt(row, 0);
        }
        master.handleDecisionRequest(approval, advID, userID);
        master.handleModMyTableRequest(userID);
    }//GEN-LAST:event_approveButtonActionPerformed

    //Moderator can claim the advertisement, the Button retrieves the selected row,
    //and passes the selected advertisement's ID to the controller to have 
    //the claim status changed.
    private void claimAdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimAdButtonActionPerformed
        // TODO add your handling code here:
        int row = this.unclaimedAdvertisementsTable.getSelectedRow();
        if(row>=0){
            advID=(String)unclaimedAdvertisementsTable.getValueAt(row, 0);
        }
        master.handleClaimRequest(advID, userID);
        category=categoryComboBox.getSelectedItem().toString();
        months_ago = periodComboBox.getSelectedItem().toString();
        this.keyword = descriptionTextField.getText();
        master.handleModSTDTableRequest(userID, category, months_ago, keyword);
    }//GEN-LAST:event_claimAdButtonActionPerformed

    //Acts similar to ComboBox, where the date - the time frame of the ad's creation -
    //is searched on a basis between "last 3, 6, 12, or all" months. The box will 
    //only change the variable "date".
    private void periodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodComboBoxActionPerformed

    private void disapproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disapproveButtonActionPerformed
        // TODO add your handling code here:
        int row = this.myAdvertisementsTable.getSelectedRow();
        approval = false; //false means disapproved
        if(row>=0){
            advID=(String)myAdvertisementsTable.getValueAt(row, 0);
        }
        master.handleDecisionRequest(approval, advID, userID);
        master.handleModMyTableRequest(userID);
    }//GEN-LAST:event_disapproveButtonActionPerformed

    private void myAdvertisementsPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_myAdvertisementsPanelComponentShown
        master.handleModMyTableRequest(userID);        // TODO add your handling code here:
    }//GEN-LAST:event_myAdvertisementsPanelComponentShown

    /**
     * @param args the command line arguments
     */
    
    //Populates the STD table for users in the view
    public void populateSTDTable(Object[][] pending_data){
        this.unclaimedAdvertisementsTable.setModel(new DefaultTableModel(pending_data, unclaimedAdvertisementsTableColumns));
        noSTDresultsLabel.setVisible(false);
    }
    
    //Populates the personal table for the user in the view
    public void populateMyTable(Object[][] claimed_data){
        this.myAdvertisementsTable.setModel(new DefaultTableModel(claimed_data, myAdvertisementsTableColumns));
        noMyResultsLabel.setVisible(false);
    }
    
    public void resetSTDTable () {
        DefaultTableModel model = (DefaultTableModel) unclaimedAdvertisementsTable.getModel();
        model.setRowCount(0);
        noSTDresultsLabel.setVisible(true);
    }
    
    public void resetMyTable () {
        DefaultTableModel model = (DefaultTableModel) myAdvertisementsTable.getModel();
        model.setRowCount(0);
        noMyResultsLabel.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advertisementsPanel;
    private javax.swing.JButton approveButton;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton claimAdButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton goButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel myAdvertisementsPanel;
    private javax.swing.JTabbedPane myAdvertisementsTabPane;
    private javax.swing.JTable myAdvertisementsTable;
    private javax.swing.JLabel noMyResultsLabel;
    private javax.swing.JLabel noSTDresultsLabel;
    private javax.swing.JComboBox<String> periodComboBox;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JTable unclaimedAdvertisementsTable;
    // End of variables declaration//GEN-END:variables
}
